/**
 * Module 1
 * Extracted from chunk.vendor.js
 *
 * Original: Gravit Designer by Corel
 * Reverse engineered for educational purposes
 *
 * Note: This is minified code. Variable names are compressed.
 * Common patterns:
 *   e = exports object
 *   t = module object
 *   n = require function
 *   i, o, a, r, s, l, c, h, u, d = local variables
 */

function (e, t, i) {
  e.exports = {
    GScene: i(160),
    GSceneOptions: i(207),
    GRGBColor: i(17),
    GParameterizedVertexProcessor: i(528),
    GOpenTypeFont: i(587),
    GText: i(70),
    GFont: i(108),
    GOpenTypeUtil: i(726),
    GObject: i(0),
    GEvent: i(72),
    GEventTarget: i(75),
    GLocale: i(9),
    GSystem: i(176),
    GFontManager: i(281),
    GUtil: i(11),
    GWorkspace: i(280),
    GTransform: i(7),
    GElement: i(22),
    GItem: i(104),
    GGradient: i(138),
    GBlock: i(69),
    GPattern: i(50),
    GNode: i(2),
    GTransactionRecorder: i(471),
    GColor: i(68),
    GColorHelper: i(648),
    GTexturePattern: i(139),
    GNoisePattern: i(518),
    GRect: i(6),
    GCompoundPath: i(113),
    GSimpleShape: i(530),
    GVertexSource: i(87),
    GPathsGraph: i(162),
    GPath: i(60),
    GPathBase: i(45),
    GImage: i(95),
    GCollabText: i(531),
    GCollaborativeTextAnnotation: i(533),
    GActionable: i(327),
    GAnnotable: i(532),
    GActionItem: i(727),
    GImageGrid: i(534),
    GPathUtil: i(179),
    GCompoundShape: i(233),
    GLayer: i(159),
    GGroup: i(122),
    GSymbol: i(216),
    GSceneUtil: i(1001),
    GRectangle: i(73),
    GPoint: i(5),
    GVertexPolyBoolean: i(264),
    GLength: i(132),
    GVertexOffsetter: i(651),
    GMath: i(12),
    GScenePaintConfiguration: i(133),
    GStylable: i(28),
    GBitmap: i(345),
    GVertexSimplifier: i(1002),
    GShape: i(56),
    GVertexContainer: i(54),
    GImageTracer: i(1003),
    GVertex: i(48),
    GPaintCanvas: i(14),
    GPaintContext: i(228),
    GPGEdge: i(347),
    GPGFacet: i(656),
    GPolygon: i(284),
    GEllipse: i(214),
    GSlice: i(289),
    GStyle: i(511),
    GHitResult: i(229),
    GVertexTransformer: i(63),
    GGLBulgePinchEffect: i(1004),
    GGLEdgeWorkEffect: i(1005),
    GBlurEffect: i(249),
    GInnerShadowEffect: i(432),
    GGLNoiseEffect: i(661),
    GDropShadowEffect: i(321),
    GGLSepiaEffect: i(728),
    GGLColorHalfToneEffect: i(1006),
    GGLHexagonalEffect: i(1007),
    GColorGradingEffect: i(1008),
    GGLInnerGlowEffect: i(1010),
    GGLZoomBlurEffect: i(839),
    GGLToonEffect: i(1011),
    GGLBloomEffect: i(1012),
    GGLTrueBlurEffect: i(1013),
    GGLDenoiseEffect: i(1014),
    GGLOuterGlowEffect: i(1015),
    GOverlayEffect: i(729),
    GGLBlurEffect: i(282),
    GGLBrightnessContrastEffect: i(730),
    GGLSwirlEffect: i(1016),
    GGLVignetteEffect: i(1017),
    GGLStrokeLayerEffect: i(1018),
    GGLInkEffect: i(1019),
    GGLUnsharpMaskEffect: i(1020),
    GGLVibranceEffect: i(1021),
    GGLDotScreenEffect: i(731),
    GGLSketchEffect: i(1022),
    GGLLensBlurEffect: i(1023),
    GGLHueSaturationEffect: i(732),
    GGLColorAdjustEffect: i(588),
    GGLTiltShiftEffect: i(1024),
    GGLRecolourEffect: i(1025),
    GColorAdjustMultiEffect: i(1026),
    GAdjustMultiEffect: i(1027),
    GMultiEffect: i(535),
    GMirrorEffect: i(840),
    GContactShadowEffect: i(1028),
    GCurvedShadowEffect: i(1029),
    GLongShadowEffect: i(1031),
    GGLBendEffect: i(1032),
    GGLDrunkEffect: i(1033),
    GGLFisheyeEffect: i(1034),
    GLinearGradient: i(147),
    GCMYKColor: i(188),
    GHSVColor: i(649),
    GRadialGradient: i(158),
    GAngularGradient: i(283),
    GBackground: i(265),
    GTLPathTextTransformer: i(215),
    GTLDirectionTextTransformer: i(266),
    GTLUtil: i(161),
    GLocaleLanguage: i(457),
    GLocaleKey: i(47),
    GVertexInfo: i(59),
    GPage: i(83),
    GDictionary: i(227),
    GSwatch: i(517),
    GSwatches: i(662),
    GWebGLEffect: i(51),
    GConnector: i(268),
    GRendererCtx: i(111),
    GRendererCtxDbg: i(205),
    GComment: i(366),
    GAnnotation: i(84),
    GAnnotationsList: i(506),
    GEmptyAnnotation: i(1035),
    GTextAnnotation: i(370),
    GHighlighterAnnotation: i(318),
    GPencilAnnotation: i(320),
    GCommentAnnotation: i(285),
    GArrowAnnotation: i(319),
    GRectangleAnnotation: i(316),
    GEllipseAnnotation: i(317),
    GDate: i(142),
    GRendererConfig: i(166),
    GSceneDictionary: i(658),
    GTranslation: i(224).GTranslation,
    GTranslationNotificationEvent: i(224).GTranslationNotificationEvent,
    GTranslationEvents: i(224).GTranslationEvents
  }, i(507);
}
