/**
 * Module 1203
 * Extracted from chunk.vendor.js
 *
 * Original: Gravit Designer by Corel
 * Reverse engineered for educational purposes
 *
 * Note: This is minified code. Variable names are compressed.
 * Common patterns:
 *   e = exports object
 *   t = module object
 *   n = require function
 *   i, o, a, r, s, l, c, h, u, d = local variables
 */

function (e, t, i) {
  var n = i(11);
  function r() {
  }
  r._list = [
    "ABeeZee",
    "Abel",
    "Abril Fatface",
    "Aclonica",
    "Acme",
    "Actor",
    "Adamina",
    "Advent Pro",
    "Aguafina Script",
    "Akronim",
    "Aladin",
    "Aldrich",
    "Alef",
    "Alegreya",
    "Alegreya Sans",
    "Alegreya Sans SC",
    "Alex Brush",
    "Alfa Slab One",
    "Alice",
    "Alike",
    "Alike Angular",
    "Allan",
    "Allerta",
    "Allerta Stencil",
    "Allura",
    "Almendra",
    "Almendra Display",
    "Almendra SC",
    "Amarante",
    "Amaranth",
    "Amatic SC",
    "Amethysta",
    "Amiri",
    "Amita",
    "Anaheim",
    "Andada",
    "Andika",
    "Annie Use Your Telescope",
    "Anonymous Pro",
    "Antic",
    "Antic Didone",
    "Antic Slab",
    "Arapey",
    "Arbutus",
    "Arbutus Slab",
    "Architects Daughter",
    "Archivo Black",
    "Archivo Narrow",
    "Arizonia",
    "Armata",
    "Artifika",
    "Arvo",
    "Arya",
    "Asap",
    "Asar",
    "Asset",
    "Astloch",
    "Asul",
    "Atomic Age",
    "Aubrey",
    "Audiowide",
    "Autour One",
    "Average",
    "Average Sans",
    "Averia Gruesa Libre",
    "Averia Libre",
    "Averia Sans Libre",
    "Averia Serif Libre",
    "Bad Script",
    "Balthazar",
    "Bangers",
    "Basic",
    "Baumans",
    "Belgrano",
    "Belleza",
    "BenchNine",
    "Bentham",
    "Berkshire Swash",
    "Bevan",
    "Bigelow Rules",
    "Bigshot One",
    "Bilbo",
    "Bilbo Swash Caps",
    "Biryani",
    "Bitter",
    "Black Ops One",
    "Bonbon",
    "Boogaloo",
    "Bowlby One",
    "Bowlby One SC",
    "Brawler",
    "Bree Serif",
    "Bubblegum Sans",
    "Bubbler One",
    "Buda",
    "Butcherman",
    "Butterfly Kids",
    "Cabin",
    "Cabin Condensed",
    "Cabin Sketch",
    "Caesar Dressing",
    "Cagliostro",
    "Calligraffitti",
    "Cambay",
    "Cambo",
    "Candal",
    "Cantarell",
    "Cantata One",
    "Cantora One",
    "Capriola",
    "Carme",
    "Carrois Gothic",
    "Carrois Gothic SC",
    "Carter One",
    "Catamaran",
    "Caudex",
    "Caveat",
    "Caveat Brush",
    "Cedarville Cursive",
    "Ceviche One",
    "Changa One",
    "Chango",
    "Chau Philomene One",
    "Chela One",
    "Chelsea Market",
    "Cherry Cream Soda",
    "Cherry Swash",
    "Chewy",
    "Chicle",
    "Chivo",
    "Chonburi",
    "Cinzel",
    "Cinzel Decorative",
    "Clicker Script",
    "Coda Caption",
    "Codystar",
    "Combo",
    "Comfortaa",
    "Coming Soon",
    "Concert One",
    "Condiment",
    "Contrail One",
    "Convergence",
    "Cookie",
    "Copse",
    "Corben",
    "Courgette",
    "Coustard",
    "Covered By Your Grace",
    "Crafty Girls",
    "Creepster",
    "Crete Round",
    "Crimson Text",
    "Croissant One",
    "Crushed",
    "Cuprum",
    "Cutive",
    "Cutive Mono",
    "Damion",
    "Dancing Script",
    "Dawning of a New Day",
    "Days One",
    "Dekko",
    "Delius",
    "Delius Swash Caps",
    "Delius Unicase",
    "Della Respira",
    "Denk One",
    "Devonshire",
    "Dhurjati",
    "Diplomata",
    "Diplomata SC",
    "Domine",
    "Donegal One",
    "Doppio One",
    "Dorsa",
    "Dosis",
    "Dr Sugiyama",
    "Droid Sans",
    "Droid Sans Mono",
    "Droid Serif",
    "Duru Sans",
    "Dynalight",
    "Eagle Lake",
    "Eater",
    "EB Garamond",
    "Economica",
    "Eczar",
    "Electrolize",
    "Elsie",
    "Elsie Swash Caps",
    "Emblema One",
    "Emilys Candy",
    "Engagement",
    "Englebert",
    "Enriqueta",
    "Erica One",
    "Esteban",
    "Euphoria Script",
    "Ewert",
    "Exo",
    "Exo 2",
    "Expletus Sans",
    "Fanwood Text",
    "Fascinate",
    "Fascinate Inline",
    "Faster One",
    "Fauna One",
    "Federant",
    "Federo",
    "Felipa",
    "Fenix",
    "Finger Paint",
    "Fira Mono",
    "Fira Sans",
    "Fjalla One",
    "Fjord One",
    "Flamenco",
    "Flavors",
    "Fondamento",
    "Fontdiner Swanky",
    "Forum",
    "Francois One",
    "Freckle Face",
    "Fredericka the Great",
    "Fredoka One",
    "Fresca",
    "Frijole",
    "Fruktur",
    "Fugaz One",
    "Gabriela",
    "Gafata",
    "Galdeano",
    "Galindo",
    "Gentium Basic",
    "Gentium Book Basic",
    "Geo",
    "Geostar",
    "Geostar Fill",
    "Germania One",
    "Gidugu",
    "Gilda Display",
    "Give You Glory",
    "Glass Antiqua",
    "Glegoo",
    "Gloria Hallelujah",
    "Goblin One",
    "Gochi Hand",
    "Gorditas",
    "Goudy Bookletter 1911",
    "Graduate",
    "Grand Hotel",
    "Gravitas One",
    "Great Vibes",
    "Griffy",
    "Gruppo",
    "Gudea",
    "Habibi",
    "Halant",
    "Hammersmith One",
    "Hanalei",
    "Hanalei Fill",
    "Handlee",
    "Happy Monkey",
    "Headland One",
    "Henny Penny",
    "Herr Von Muellerhoff",
    "Hind",
    "Hind Siliguri",
    "Hind Vadodara",
    "Holtwood One SC",
    "Homemade Apple",
    "Homenaje",
    "Iceberg",
    "Iceland",
    "IM Fell Double Pica",
    "IM Fell Double Pica SC",
    "IM Fell DW Pica",
    "IM Fell DW Pica SC",
    "IM Fell English",
    "IM Fell English SC",
    "IM Fell French Canon",
    "IM Fell French Canon SC",
    "IM Fell Great Primer",
    "IM Fell Great Primer SC",
    "Imprima",
    "Inconsolata",
    "Inder",
    "Indie Flower",
    "Inika",
    "Inknut Antiqua",
    "Irish Grover",
    "Istok Web",
    "Italiana",
    "Italianno",
    "Itim",
    "Jacques Francois",
    "Jacques Francois Shadow",
    "Jaldi",
    "Jim Nightshade",
    "Jockey One",
    "Jolly Lodger",
    "Josefin Sans",
    "Josefin Slab",
    "Joti One",
    "Judson",
    "Julee",
    "Julius Sans One",
    "Junge",
    "Jura",
    "Just Another Hand",
    "Just Me Again Down Here",
    "Kadwa",
    "Kalam",
    "Kameron",
    "Kanit",
    "Karla",
    "Karma",
    "Kaushan Script",
    "Kavoon",
    "Keania One",
    "Kelly Slab",
    "Kenia",
    "Khand",
    "Khula",
    "Kite One",
    "Knewave",
    "Kotta One",
    "Kranky",
    "Kreon",
    "Kristi",
    "Krona One",
    "Kurale",
    "La Belle Aurore",
    "Laila",
    "Lakki Reddy",
    "Lancelot",
    "Lateef",
    "Lato",
    "League Script",
    "Leckerli One",
    "Ledger",
    "Lekton",
    "Lemon",
    "Libre Baskerville",
    "Life Savers",
    "Lilita One",
    "Lily Script One",
    "Limelight",
    "Linden Hill",
    "Lobster",
    "Lobster Two",
    "Londrina Outline",
    "Londrina Shadow",
    "Londrina Sketch",
    "Londrina Solid",
    "Lora",
    "Love Ya Like A Sister",
    "Loved by the King",
    "Lovers Quarrel",
    "Luckiest Guy",
    "Lusitana",
    "Lustria",
    "Macondo",
    "Macondo Swash Caps",
    "Magra",
    "Maiden Orange",
    "Mako",
    "Mallanna",
    "Mandali",
    "Marcellus",
    "Marcellus SC",
    "Marck Script",
    "Margarine",
    "Marko One",
    "Marmelad",
    "Martel",
    "Martel Sans",
    "Marvel",
    "Mate",
    "Mate SC",
    "Maven Pro",
    "McLaren",
    "Meddon",
    "MedievalSharp",
    "Medula One",
    "Megrim",
    "Meie Script",
    "Merienda",
    "Merienda One",
    "Merriweather",
    "Merriweather Sans",
    "Metal Mania",
    "Metamorphous",
    "Metrophobic",
    "Michroma",
    "Milonga",
    "Miltonian",
    "Miltonian Tattoo",
    "Miniver",
    "Miss Fajardose",
    "Modak",
    "Modern Antiqua",
    "Molengo",
    "Molle",
    "Monda",
    "Monofett",
    "Monoton",
    "Monsieur La Doulaise",
    "Montaga",
    "Montez",
    "Montserrat",
    "Montserrat Alternates",
    "Montserrat Subrayada",
    "Mountains of Christmas",
    "Mouse Memoirs",
    "Mr Bedfort",
    "Mr Dafoe",
    "Mr De Haviland",
    "Mrs Saint Delafield",
    "Mrs Sheppards",
    "Muli",
    "Mystery Quest",
    "Neucha",
    "Neuton",
    "New Rocker",
    "News Cycle",
    "Niconne",
    "Nixie One",
    "Nobile",
    "Norican",
    "Nosifer",
    "Nothing You Could Do",
    "Noticia Text",
    "Noto Sans",
    "Noto Serif",
    "Nova Cut",
    "Nova Flat",
    "Nova Mono",
    "Nova Oval",
    "Nova Round",
    "Nova Script",
    "Nova Slim",
    "Nova Square",
    "Numans",
    "Nunito",
    "Offside",
    "Old Standard TT",
    "Oldenburg",
    "Oleo Script",
    "Oleo Script Swash Caps",
    "Open Sans",
    "Open Sans Condensed",
    "Oranienbaum",
    "Orbitron",
    "Oregano",
    "Orienta",
    "Original Surfer",
    "Oswald",
    "Over the Rainbow",
    "Overlock",
    "Overlock SC",
    "Ovo",
    "Oxygen",
    "Oxygen Mono",
    "Pacifico",
    "Palanquin",
    "Palanquin Dark",
    "Paprika",
    "Parisienne",
    "Passero One",
    "Passion One",
    "Pathway Gothic One",
    "Patrick Hand",
    "Patrick Hand SC",
    "Patua One",
    "Paytone One",
    "Peddana",
    "Peralta",
    "Permanent Marker",
    "Petit Formal Script",
    "Petrona",
    "Philosopher",
    "Piedra",
    "Pinyon Script",
    "Pirata One",
    "Plaster",
    "Playball",
    "Playfair Display",
    "Playfair Display SC",
    "Podkova",
    "Poiret One",
    "Poller One",
    "Poly",
    "Pompiere",
    "Pontano Sans",
    "Poppins",
    "Port Lligat Sans",
    "Port Lligat Slab",
    "Pragati Narrow",
    "Prata",
    "Press Start 2P",
    "Princess Sofia",
    "Prociono",
    "Prosto One",
    "PT Mono",
    "PT Sans",
    "PT Sans Caption",
    "PT Sans Narrow",
    "PT Serif",
    "PT Serif Caption",
    "Puritan",
    "Purple Purse",
    "Quando",
    "Quantico",
    "Quattrocento",
    "Quattrocento Sans",
    "Questrial",
    "Quicksand",
    "Quintessential",
    "Qwigley",
    "Racing Sans One",
    "Radley",
    "Rajdhani",
    "Raleway",
    "Raleway Dots",
    "Ramabhadra",
    "Ramaraja",
    "Rambla",
    "Rammetto One",
    "Ranchers",
    "Rancho",
    "Ranga",
    "Rationale",
    "Ravi Prakash",
    "Redressed",
    "Reenie Beanie",
    "Revalia",
    "Rhodium Libre",
    "Ribeye",
    "Ribeye Marrow",
    "Righteous",
    "Risque",
    "Roboto",
    "Roboto Condensed",
    "Roboto Mono",
    "Roboto Slab",
    "Rochester",
    "Rock Salt",
    "Rokkitt",
    "Romanesco",
    "Ropa Sans",
    "Rosario",
    "Rosarivo",
    "Rouge Script",
    "Rozha One",
    "Rubik",
    "Rubik Mono One",
    "Rubik One",
    "Ruda",
    "Rufina",
    "Ruge Boogie",
    "Ruluko",
    "Rum Raisin",
    "Ruslan Display",
    "Russo One",
    "Ruthie",
    "Rye",
    "Sacramento",
    "Sahitya",
    "Sail",
    "Salsa",
    "Sanchez",
    "Sancreek",
    "Sansita One",
    "Sarala",
    "Sarina",
    "Sarpanch",
    "Satisfy",
    "Scada",
    "Scheherazade",
    "Schoolbell",
    "Seaweed Script",
    "Sevillana",
    "Seymour One",
    "Shadows Into Light",
    "Shadows Into Light Two",
    "Shanti",
    "Share",
    "Share Tech",
    "Share Tech Mono",
    "Shojumaru",
    "Short Stack",
    "Sigmar One",
    "Signika",
    "Signika Negative",
    "Simonetta",
    "Sintony",
    "Sirin Stencil",
    "Six Caps",
    "Skranji",
    "Slabo 13px",
    "Slabo 27px",
    "Slackey",
    "Smokum",
    "Smythe",
    "Sniglet",
    "Snippet",
    "Snowburst One",
    "Sofadi One",
    "Sofia",
    "Sonsie One",
    "Sorts Mill Goudy",
    "Source Code Pro",
    "Source Sans Pro",
    "Source Serif Pro",
    "Special Elite",
    "Spicy Rice",
    "Spinnaker",
    "Spirax",
    "Squada One",
    "Sree Krushnadevaraya",
    "Stalemate",
    "Stalinist One",
    "Stardos Stencil",
    "Stint Ultra Condensed",
    "Stint Ultra Expanded",
    "Stoke",
    "Strait",
    "Sue Ellen Francisco",
    "Sumana",
    "Sunshiney",
    "Supermercado One",
    "Sura",
    "Suranna",
    "Swanky and Moo Moo",
    "Syncopate",
    "Tangerine",
    "Tauri",
    "Teko",
    "Telex",
    "Tenali Ramakrishna",
    "Tenor Sans",
    "Text Me One",
    "The Girl Next Door",
    "Tienne",
    "Tillana",
    "Timmana",
    "Tinos",
    "Titan One",
    "Titillium Web",
    "Trade Winds",
    "Trocchi",
    "Trochut",
    "Trykker",
    "Tulpen One",
    "Ubuntu",
    "Ubuntu Condensed",
    "Ubuntu Mono",
    "Ultra",
    "Uncial Antiqua",
    "Underdog",
    "Unica One",
    "UnifrakturCook",
    "UnifrakturMaguntia",
    "Unkempt",
    "Unlock",
    "Unna",
    "Vampiro One",
    "Varela",
    "Varela Round",
    "Vast Shadow",
    "Vesper Libre",
    "Vibur",
    "Vidaloka",
    "Viga",
    "Voces",
    "Volkhov",
    "Vollkorn",
    "Voltaire",
    "VT323",
    "Waiting for the Sunrise",
    "Wallpoet",
    "Walter Turncoat",
    "Warnes",
    "Wellfleet",
    "Wendy One",
    "Wire One",
    "Work Sans",
    "Yanone Kaffeesatz",
    "Yantramanav",
    "Yellowtail",
    "Yeseva One",
    "Yesteryear",
    "Zeyada"
  ], r.updateList = function (e) {
    this._list = (e || []).slice();
  }, r.contains = function (e) {
    return n.find(this._list, function (t) {
      return t.toLowerCase() === e.toLowerCase();
    });
  }, e.exports = r;
}
