/**
 * Webpack Module #10
 * Type: unknown
 */

function (exports, module, require) {
    "use strict";
    var o = n(15) /* module_15 */;
    const i = n(519) /* module_519 */,
      a = n(520) /* module_520 */,
      r = n(231) /* module_231 */;
    (i.GoogleTagManagerSettings = n(820) /* module_820 */),
      (i.AUTO_SAVE_ENABLED =
        o.GPlatform.webBrowser !== o.GPlatform.constructor.WebBrowser.Safari),
      (i.DOMAIN = window.location.host),
      (i.GA = { customDimensions: ["EWOSU", "token", "template", "preset"] }),
      (i.PURCHASE = {
        URL_TO_PRODUCT: { purchase_flow: 214093, purchase_flow_new: 220444 },
      }),
      (i.LEGACY_SHARE_DIALOG = false),
      (i.ENABLE_COLLABORATION = true),
      (i.FILE_REVIEW_ENABLED = true),
      (i.ENABLE_REQUEST_ACCESS = true),
      (i.ENABLE_GUEST_ACCESS = true),
      (i.IN_APP_PURCHASE.WINDOWS.production = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.beta = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.lts = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.rc = "GravitDesignerSubscription-rc"),
      (i.IN_APP_PURCHASE.WINDOWS.trunk = "GravitDesignerSubscription-trunk"),
      (i.IN_APP_PURCHASE.CLEVERBRIDGE.openCartInAPopup = true),
      (i.websocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.trunkWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.rcWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.betaWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.cloudURL = window.location.origin),
      (i.cloudTrunkURL = window.location.origin),
      (i.cloudBetaURL = window.location.origin),
      (i.cloudRCURL = window.location.origin),
      (i.trunkURL = window.location.origin),
      (i.betaURL = window.location.origin),
      (i.ltsURL = window.location.origin),
      (i.rcURL = window.location.origin),
      (i.prodURL = window.location.origin),
      (i.domain = window.location.host),
      (i.gApi = n(417) /* module_417 */),
      (i.DateAPI = n(209) /* module_209 */.DateAPI),
      (i.GLocaleFactory = n(209) /* module_209 */.GLocale),
      (i.defaultUserSettings = n(253) /* module_253 */),
      (i.i18n = {
        trunk: "https://d2mocl49mz6ak6.cloudfront.net/trunk/locale",
        staging: "https://d2mocl49mz6ak6.cloudfront.net/staging/locale",
        preview: "https://d2mocl49mz6ak6.cloudfront.net/preview/locale",
        production: "https://d2mocl49mz6ak6.cloudfront.net/production/locale",
      }),
      (i.SharePermissions = n(352) /* module_352 */),
      (i.ShareRoles = n(287) /* module_287 */),
      (i.Share = n(575) /* module_575 */),
      (i.Lock = n(579) /* module_579 */),
      (i.FileExtended = n(574) /* module_574 */),
      (i.FileTypes = n(825) /* module_825 */),
      (i.MicrosoftB2BKeyType = n(826) /* module_826 */),
      (i.PaymentProviders = n(577) /* module_577 */),
      (i.PurchaseStatus = n(827) /* module_827 */),
      (i.SubscriptionStatus = n(828) /* module_828 */),
      (i.PasswordlessAuthenticationActions = n(580) /* module_580 */),
      (i.PasswordRules = n(581) /* module_581 */),
      (i.License = n(829) /* module_829 */),
      (i.LicenseType = n(430) /* module_430 */),
      (i.Runtime = n(582) /* module_582 */),
      (i.User = n(830) /* module_830 */),
      (i.CloudUtils = n(254) /* module_254 */),
      (i.UTM = n(354) /* module_354 */),
      r.IS_WEB_WORKER ||
        ((i.GLoginDialog = n(270) /* module_270 */.GLoginDialog),
        (i.GReminderDialogFactory = n(270) /* module_270 */.GReminderDialogFactory),
        (i.GReminderDialog = n(270) /* module_270 */.GReminderDialog),
        (i.GPaywallDialog = n(270) /* module_270 */.GPaywallDialog)),
      (i.PRESET_LIMIT = 20),
      (i.CATEGORIES = n(831) /* module_831 */),
      (i.ELEMENTS = n(832) /* module_832 */),
      (i.GooglePickerBuilder = n(833) /* module_833 */),
      (i.HAS_ANNOTATIONS = true),
      (i.ANNOTATION_PERMANENT_LINK = true),
      (i.ANONYMOUS_SESSION_ENABLED = true),
      (i.USE_EXTENSION_IN_FILENAME = false),
      (i.ALWAYS_SHOW_ACCOUNT_SETTING_DIALOG = false),
      (i.Notification = n(834) /* module_834 */),
      (i.NotificationConstants = n(585) /* module_585 */),
      (i.FileStatus = n(586) /* module_586 */),
      (i.FileReviewStatusAvailable = [
        i.FileStatus.IN_REVIEW,
        i.FileStatus.REOPENED,
        i.FileStatus.AWAITING_APPROVAL,
        i.FileStatus.APPROVED,
      ]),
      (i.GFileReviewFlow = n(835) /* module_835 */),
      (i.GFileReviewActions = n(836) /* module_836 */);
    const s = n(583) /* module_583 */;
    (i.NOTIFICATION_USER_MENTION_REGEX = s.NOTIFICATION.USER_MENTION),
      (i.HTTP_STATUS_CODES = n(578) /* module_578 */),
      (i.CloudIntegration = {
        cloudOptions: [
          {
            name: "Google Drive",
            type: "googledrive",
            className: "google-drive",
            pro: true,
            default: false,
          },
        ],
        nativeOption: {
          type: "native",
          name: "Gravit Designer",
          deletable: false,
          pro: false,
          id: a.Provider.CloudNative,
          default: true,
        },
      }),
      (i.PAGE_CLIP_DEFAULT = true),
      (i.msTeamsMode = false),
      (i.thirdPartyCookieWarningLink = ""),
      (i.LINKS.BLENDING_MODES_DOCUMENTATION_URL = ""),
      (i.AmplitudeHelper = n(584) /* module_584 */),
      (i.AmplitudeData = n(431) /* module_431 */),
      (e.exports = i);
  }