/**
 * Webpack Module #10
 * Type: unknown
 */

function (exports, module, require) {
    "use strict";
    var o = require(15) /* module */;
    const i = require(519) /* module_519 */,
      a = require(520) /* module_520 */,
      r = require(231) /* module_231 */;
    (i.GoogleTagManagerSettings = require(820) /* module */),
      (i.AUTO_SAVE_ENABLED =
        o.GPlatform.webBrowser !== o.GPlatform.constructor.WebBrowser.Safari),
      (i.DOMAIN = window.location.host),
      (i.GA = { customDimensions: ["EWOSU", "token", "template", "preset"] }),
      (i.PURCHASE = {
        URL_TO_PRODUCT: { purchase_flow: 214093, purchase_flow_new: 220444 },
      }),
      (i.LEGACY_SHARE_DIALOG = false),
      (i.ENABLE_COLLABORATION = true),
      (i.FILE_REVIEW_ENABLED = true),
      (i.ENABLE_REQUEST_ACCESS = true),
      (i.ENABLE_GUEST_ACCESS = true),
      (i.IN_APP_PURCHASE.WINDOWS.production = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.beta = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.lts = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.rc = "GravitDesignerSubscription-rc"),
      (i.IN_APP_PURCHASE.WINDOWS.trunk = "GravitDesignerSubscription-trunk"),
      (i.IN_APP_PURCHASE.CLEVERBRIDGE.openCartInAPopup = true),
      (i.websocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.trunkWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.rcWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.betaWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.cloudURL = window.location.origin),
      (i.cloudTrunkURL = window.location.origin),
      (i.cloudBetaURL = window.location.origin),
      (i.cloudRCURL = window.location.origin),
      (i.trunkURL = window.location.origin),
      (i.betaURL = window.location.origin),
      (i.ltsURL = window.location.origin),
      (i.rcURL = window.location.origin),
      (i.prodURL = window.location.origin),
      (i.domain = window.location.host),
      (i.gApi = require(417) /* module */),
      (i.DateAPI = require(209) /* module */.DateAPI),
      (i.GLocaleFactory = require(209) /* module */.GLocale),
      (i.defaultUserSettings = require(253) /* module */),
      (i.i18n = {
        trunk: "https://d2mocl49mz6ak6.cloudfront.net/trunk/locale",
        staging: "https://d2mocl49mz6ak6.cloudfront.net/staging/locale",
        preview: "https://d2mocl49mz6ak6.cloudfront.net/preview/locale",
        production: "https://d2mocl49mz6ak6.cloudfront.net/production/locale",
      }),
      (i.SharePermissions = require(352) /* module */),
      (i.ShareRoles = require(287) /* module */),
      (i.Share = require(575) /* module */),
      (i.Lock = require(579) /* module */),
      (i.FileExtended = require(574) /* module */),
      (i.FileTypes = require(825) /* module */),
      (i.MicrosoftB2BKeyType = require(826) /* module */),
      (i.PaymentProviders = require(577) /* module */),
      (i.PurchaseStatus = require(827) /* module */),
      (i.SubscriptionStatus = require(828) /* module */),
      (i.PasswordlessAuthenticationActions = require(580) /* module */),
      (i.PasswordRules = require(581) /* module */),
      (i.License = require(829) /* module */),
      (i.LicenseType = require(430) /* module */),
      (i.Runtime = require(582) /* module */),
      (i.User = require(830) /* GCommonNames */),
      (i.CloudUtils = require(254) /* GCommonNames */),
      (i.UTM = require(354) /* module */),
      r.IS_WEB_WORKER ||
        ((i.GLoginDialog = require(270) /* module */.GLoginDialog),
        (i.GReminderDialogFactory = require(270) /* module */.GReminderDialogFactory),
        (i.GReminderDialog = require(270) /* module */.GReminderDialog),
        (i.GPaywallDialog = require(270) /* module */.GPaywallDialog)),
      (i.PRESET_LIMIT = 20),
      (i.CATEGORIES = require(831) /* module */),
      (i.ELEMENTS = require(832) /* module */),
      (i.GooglePickerBuilder = require(833) /* module */),
      (i.HAS_ANNOTATIONS = true),
      (i.ANNOTATION_PERMANENT_LINK = true),
      (i.ANONYMOUS_SESSION_ENABLED = true),
      (i.USE_EXTENSION_IN_FILENAME = false),
      (i.ALWAYS_SHOW_ACCOUNT_SETTING_DIALOG = false),
      (i.Notification = require(834) /* module */),
      (i.NotificationConstants = require(585) /* module */),
      (i.FileStatus = require(586) /* module */),
      (i.FileReviewStatusAvailable = [
        i.FileStatus.IN_REVIEW,
        i.FileStatus.REOPENED,
        i.FileStatus.AWAITING_APPROVAL,
        i.FileStatus.APPROVED,
      ]),
      (i.GFileReviewFlow = require(835) /* module */),
      (i.GFileReviewActions = require(836) /* module */);
    const s = require(583) /* module */;
    (i.NOTIFICATION_USER_MENTION_REGEX = s.NOTIFICATION.USER_MENTION),
      (i.HTTP_STATUS_CODES = require(578) /* module */),
      (i.CloudIntegration = {
        cloudOptions: [
          {
            name: "Google Drive",
            type: "googledrive",
            className: "google-drive",
            pro: true,
            default: false,
          },
        ],
        nativeOption: {
          type: "native",
          name: "Gravit Designer",
          deletable: false,
          pro: false,
          id: a.Provider.CloudNative,
          default: true,
        },
      }),
      (i.PAGE_CLIP_DEFAULT = true),
      (i.msTeamsMode = false),
      (i.thirdPartyCookieWarningLink = ""),
      (i.LINKS.BLENDING_MODES_DOCUMENTATION_URL = ""),
      (i.AmplitudeHelper = require(584) /* module */),
      (i.AmplitudeData = require(431) /* module */),
      (exports.exports = i);
  }