/**
 * Webpack Module #1072
 * Type: unknown
 */

function (exports, module, require) {
    "use strict";
    exports.exports = {
      DELETE_COMMENT_ANNOTATION: "DELETE_COMMENT_ANNOTATION",
      RESOLVE_COMMENT_ANNOTATION: "RESOLVE_COMMENT_ANNOTATION",
      RESOLVE_ALL_COMMENT_ANNOTATION: "RESOLVE_ALL_COMMENT_ANNOTATION",
      REOPEN_COMMENT_ANNOTATION: "REOPEN_COMMENT_ANNOTATION",
    };
  }