/**
 * Module 24
 * Extracted from chunk.vendor.js
 *
 * Original: Gravit Designer by Corel
 * Reverse engineered for educational purposes
 *
 * Note: This code is minified. Variable names like e, t, n, i, o, a, r, s
 * have been compressed. Refer to the original open-source Gravit code
 * for better understanding of the logic.
 */

function (e, t, i) {
      e.exports = {
        GConnectorTool: i(738),
        GTriangleTool: i(746),
        GLassoTool: i(748),
        GTextTool: i(547),
        GRectangleTool: i(549),
        GPathsGraphTool: i(753),
        GSubSelectTool: i(386),
        GLineTool: i(550),
        GStarTool: i(754),
        GFreehandTool: i(335),
        GZoomTool: i(755),
        GHandTool: i(756),
        GPointerTool: i(548),
        GKnifeTool: i(757),
        GPenTool: i(539),
        GFillTool: i(758),
        GPolygonTool: i(384),
        GLayerTool: i(759),
        GEllipseTool: i(551),
        GBezigonTool: i(761),
        GSimpleShapeTool: i(762),
        GSliceTool: i(763),
        GGuides: i(210),
        GSelectTool: i(334),
        GMagicTool: i(764),
        GGuideLinesGuide: i(739),
        GToolManager: i(553),
        GActionManager: i(1080),
        GTool: i(211),
        GEditorOptions: i(24),
        GEditorPaintConfiguration: i(777),
        GElementEditor: i(36),
        GFullPixelsGuide: i(544),
        GEditorWorkspace: i(778),
        GPathEditor: i(127),
        GItemTool: i(332),
        GGridGuide: i(740),
        GPageLabelGuide: i(743),
        GPointsGuide: i(741),
        GPageGuide: i(742),
        GBBoxGuide: i(153),
        GEditorWidget: i(1081),
        GPolygonEditor: i(747),
        GCompoundShapeEditor: i(1082),
        GImageGridEditor: i(1083),
        GSliceEditor: i(1084),
        GSimpleShapeEditor: i(1085),
        GCompoundPathEditor: i(235),
        GGradientStyleEditor: i(276),
        GRadialGradientEditor: i(780),
        GAngularGradientEditor: i(781),
        GGroupEditor: i(751),
        GSymbolEditor: i(1086),
        GBoxEditor: i(66),
        GBaseEditor: i(39),
        GSceneEditor: i(545),
        GRectangleEditor: i(330),
        GShapeEditor: i(128),
        GItemEditor: i(274),
        GInlineTextEditor: i(752),
        GTextEditor: i(387),
        GEllipseEditor: i(552),
        GBlockEditor: i(154),
        GImageEditor: i(329),
        GCollabTextEditor: i(1087),
        GPathBaseEditor: i(155),
        GLayerEditor: i(760),
        GTransformBox: i(546),
        GLinearGradientEditor: i(782),
        GStyleEditor: i(385),
        GSelectionPositionEditor: i(745),
        GPathsGraphEditor: i(275),
        GEditor: i(82),
        GEditorAnnotation: i(81),
        GRotateAnnotation: i(542),
        GSkewVerticalAnnotation: i(750),
        GSkewHorizontalAnnotation: i(749),
        GPreserveAspectRatioAnnotation: i(543),
        GPageEditor: i(331),
        GStyleEdManager: i(779),
        GTextAnnotationEditor: i(783),
        GTextAnnotationTool: i(1088),
        GRectangleAnnotationEditor: i(768),
        GRectangleAnnotationTool: i(767),
        GEllipseAnnotationEditor: i(766),
        GEllipseAnnotationTool: i(765),
        GHighlighterAnnotationEditor: i(776),
        GHighlighterAnnotationTool: i(775),
        GPencilAnnotationEditor: i(774),
        GPencilAnnotationTool: i(773),
        GArrowAnnotationEditor: i(770),
        GCollaborativeTextAnnotationEditor: i(1089),
        GArrowAnnotationTool: i(769),
        GCommentAnnotationEditor: i(772),
        GCommentAnnotationTool: i(771),
        GAnnotationTool: i(212),
        GAnnotationEditor: i(172),
      };
    }
