/**
 * Webpack Module #10
 * Type: unknown
 */

function (e, t, n) {
    "use strict";
    var o = n(15) /* GEditor */;
    const i = n(519) /* AppSettings */,
      a = n(520) /* barrel_purchase_urls */,
      r = n(231) /* module_231 */;
    (i.GoogleTagManagerSettings = n(820) /* module */),
      (i.AUTO_SAVE_ENABLED =
        o.GPlatform.webBrowser !== o.GPlatform.constructor.WebBrowser.Safari),
      (i.DOMAIN = window.location.host),
      (i.GA = { customDimensions: ["EWOSU", "token", "template", "preset"] }),
      (i.PURCHASE = {
        URL_TO_PRODUCT: { purchase_flow: 214093, purchase_flow_new: 220444 },
      }),
      (i.LEGACY_SHARE_DIALOG = !1),
      (i.ENABLE_COLLABORATION = !0),
      (i.FILE_REVIEW_ENABLED = !0),
      (i.ENABLE_REQUEST_ACCESS = !0),
      (i.ENABLE_GUEST_ACCESS = !0),
      (i.IN_APP_PURCHASE.WINDOWS.production = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.beta = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.lts = "ESDWINGRAVIT"),
      (i.IN_APP_PURCHASE.WINDOWS.rc = "GravitDesignerSubscription-rc"),
      (i.IN_APP_PURCHASE.WINDOWS.trunk = "GravitDesignerSubscription-trunk"),
      (i.IN_APP_PURCHASE.CLEVERBRIDGE.openCartInAPopup = !0),
      (i.websocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.trunkWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.rcWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.betaWebsocketURL = (window.location.protocol === "https:" ? "wss://" : "ws://") + window.location.host + "/license"),
      (i.cloudURL = window.location.origin),
      (i.cloudTrunkURL = window.location.origin),
      (i.cloudBetaURL = window.location.origin),
      (i.cloudRCURL = window.location.origin),
      (i.trunkURL = window.location.origin),
      (i.betaURL = window.location.origin),
      (i.ltsURL = window.location.origin),
      (i.rcURL = window.location.origin),
      (i.prodURL = window.location.origin),
      (i.domain = window.location.host),
      (i.gApi = n(417) /* module */),
      (i.DateAPI = n(209) /* module */.DateAPI),
      (i.GLocaleFactory = n(209) /* module */.GLocale),
      (i.defaultUserSettings = n(253) /* module */),
      (i.i18n = {
        trunk: "https://d2mocl49mz6ak6.cloudfront.net/trunk/locale",
        staging: "https://d2mocl49mz6ak6.cloudfront.net/staging/locale",
        preview: "https://d2mocl49mz6ak6.cloudfront.net/preview/locale",
        production: "https://d2mocl49mz6ak6.cloudfront.net/production/locale",
      }),
      (i.SharePermissions = n(352) /* module */),
      (i.ShareRoles = n(287) /* module */),
      (i.Share = n(575) /* module */),
      (i.Lock = n(579) /* module */),
      (i.FileExtended = n(574) /* module */),
      (i.FileTypes = n(825) /* module */),
      (i.MicrosoftB2BKeyType = n(826) /* module */),
      (i.PaymentProviders = n(577) /* module */),
      (i.PurchaseStatus = n(827) /* module */),
      (i.SubscriptionStatus = n(828) /* module */),
      (i.PasswordlessAuthenticationActions = n(580) /* module */),
      (i.PasswordRules = n(581) /* module */),
      (i.License = n(829) /* module */),
      (i.LicenseType = n(430) /* module */),
      (i.Runtime = n(582) /* module */),
      (i.User = n(830) /* GCommonNames */),
      (i.CloudUtils = n(254) /* GCommonNames */),
      (i.UTM = n(354) /* module */),
      r.IS_WEB_WORKER ||
        ((i.GLoginDialog = n(270) /* module */.GLoginDialog),
        (i.GReminderDialogFactory = n(270) /* module */.GReminderDialogFactory),
        (i.GReminderDialog = n(270) /* module */.GReminderDialog),
        (i.GPaywallDialog = n(270) /* module */.GPaywallDialog)),
      (i.PRESET_LIMIT = 20),
      (i.CATEGORIES = n(831) /* module */),
      (i.ELEMENTS = n(832) /* module */),
      (i.GooglePickerBuilder = n(833) /* module */),
      (i.HAS_ANNOTATIONS = !0),
      (i.ANNOTATION_PERMANENT_LINK = !0),
      (i.ANONYMOUS_SESSION_ENABLED = !0),
      (i.USE_EXTENSION_IN_FILENAME = !1),
      (i.ALWAYS_SHOW_ACCOUNT_SETTING_DIALOG = !1),
      (i.Notification = n(834) /* module */),
      (i.NotificationConstants = n(585) /* module */),
      (i.FileStatus = n(586) /* module */),
      (i.FileReviewStatusAvailable = [
        i.FileStatus.IN_REVIEW,
        i.FileStatus.REOPENED,
        i.FileStatus.AWAITING_APPROVAL,
        i.FileStatus.APPROVED,
      ]),
      (i.GFileReviewFlow = n(835) /* module */),
      (i.GFileReviewActions = n(836) /* module */);
    const s = n(583) /* module */;
    (i.NOTIFICATION_USER_MENTION_REGEX = s.NOTIFICATION.USER_MENTION),
      (i.HTTP_STATUS_CODES = n(578) /* module */),
      (i.CloudIntegration = {
        cloudOptions: [
          {
            name: "Google Drive",
            type: "googledrive",
            className: "google-drive",
            pro: !0,
            default: !1,
          },
        ],
        nativeOption: {
          type: "native",
          name: "Gravit Designer",
          deletable: !1,
          pro: !1,
          id: a.Provider.CloudNative,
          default: !0,
        },
      }),
      (i.PAGE_CLIP_DEFAULT = !0),
      (i.msTeamsMode = !1),
      (i.thirdPartyCookieWarningLink = ""),
      (i.LINKS.BLENDING_MODES_DOCUMENTATION_URL = ""),
      (i.AmplitudeHelper = n(584) /* module */),
      (i.AmplitudeData = n(431) /* module */),
      (e.exports = i);
  }