/**
 * Webpack Module #519
 * Type: unknown
 */

function (e, t, n) {
    "use strict";
    const o = [
        { ext: "gvdesign", type: "application/gravit+design", default: !0 },
      ],
      i = o.map((e) => {
        let { ext: t } = e;
        return t.toLowerCase();
      });
    e.exports = {
      AmplitudeHelper: {
        logEvent() {},
        updateUserProperty() {},
        updateUserLicenseProperties() {},
      },
      AmplitudeData: { Events: {}, EventProperties: {}, UserProperties: {} },
      ENABLE_UNSPLASH_INTEGRATION: !0,
      GoogleTagManagerSettings: null,
      IN_APP_PURCHASE: {
        WINDOWS: {
          trunk: null,
          rc: null,
          beta: null,
          production: null,
          lts: null,
        },
        CLEVERBRIDGE: { openCartInAPopup: !1 },
      },
      License: null,
      LicenseType: null,
      Runtime: null,
      NOTIFICATION_USER_MENTION_REGEX: null,
      NOTIFICATION_SETTINGS_ENABLED: !1,
      FILE_REVIEW_ENABLED: !0,
      ANNOTATION_PERMANENT_LINK: !1,
      ANONYMOUS_SESSION_ENABLED: !1,
      LOCAL_FONTS_API_ENABLED: !0,
      DOMAIN: null,
      GA: { customDimensions: null },
      TOUCH_LAYOUT: !0,
      SHARE_ENGINE: !0,
      LEGACY_SHARE_DIALOG: !1,
      ENABLE_COLLABORATION: !0,
      ENABLE_REQUEST_ACCESS: !0,
      ENABLE_GUEST_ACCESS: !0,
      LISTS_FEATURE: !0,
      REMOVE_GUEST_USER_WHEN_ROLE_IS_NO_ACCESS: !1,
      PURCHASE: { URL_TO_PRODUCT: null },
      DESIGNER: { TITLE: "Gravit Designer" },
      TRANSLATION_MANAGER: { CONSIDER_EXTENSION: void 0 },
      SOFTWARE_UPDATE: {
        SHOW_CHANGE_LOG: !1,
        CHANGE_LOG_LINK: "",
      },
      LOGIN_DIALOGS: { POPUP: !0 },
      HAS_ENTERPRISE: !1,
      FORGOT_PWD_LINK: null,
      LICENSE: { UPGRADEABLE: !1 },
      CLOUD_DIALOG: { NEW_LAYOUT: !1, SHOW_FILE_SIZE_INFO: !0 },
      CLOUD_SYNC_FEATURE: { NEW_LAYOUT: !0 },
      USER_LOGIN: { SHOW_PURCHASE_PRO: !0 },
      AUTO_SAVE_ENABLED: !0,
      AUTOSAVE_INTERVALS: [5, 10, 20],
      AUTOSAVE_INTERVAL_DEFAULT: 5,
      FILE_FORMATS: o,
      FILE_EXTENSIONS: i,
      LINKS: {
        CLEVERBRIDGE_SUPPORT_URL:
          "https://support.cleverbridge.com/hc/en/requests/new?ticket_form_id=18434",
        BLENDING_MODES_DOCUMENTATION_URL: null,
        ACCOUNT_SETTING_URL: null,
        USER_NAME_UPDATE_URL: null,
      },
      FOLDER_FORMAT: "application/gravit+folder",
      HAS_SNAPZONES: !0,
      HAS_ANNOTATIONS: !1,
      PROFILE_DIALOG_URL: null,
      PRESET_LIMIT: void 0,
      CONNECTION_TEST_WITH_CREDENTIALS: !1,
      NEW_COMMENT_READ_TIMEOUT: 3e4,
      cloudTrunkURL: null,
      cloudRCURL: null,
      trunkURL: null,
      betaURL: null,
      cloudBetaURL: null,
      prodURL: null,
      rcURL: null,
      ltsURL: null,
      domain: null,
      webcdr: null,
      stagingWebcdr: null,
      betaWebcdr: null,
      trunkwebcdr: null,
      websocketURL: null,
      trunkWebsocketURL: null,
      rcWebsocketURL: null,
      betaWebsocketURL: null,
      DateAPI: null,
      gApi: null,
      GooglePickerBuilder: null,
      USE_EXTENSION_IN_FILENAME: !0,
      ALWAYS_SHOW_ACCOUNT_SETTING_DIALOG: !0,
      ALLOW_REARRANGE_TABS: !0,
      SHOW_SIDEBAR_BADGE: !0,
      COMPUTE_SHA256_FOR_FILES: !1,
      IS_COREL: !1,
      IS_TRUNK: !1,
      IS_PROD: !0,
      IS_BETA: !1,
      FILE_ID_PREFIX: {},
      GFileReviewActions: {},
      FileStatus: {},
      User: {},
      NotificationConstants: {},
      LONG_PRESS_TIME_OUT: 500,
      JPEG_EXPORT_QUALITY_DEFAULT: 92,
      VTREE_FREE_HEIGHT: 7,
      VTREE_FREE_HEIGHT_TOUCH: 15,
      UN_BELIVEVABLE_FEW_BYTES_TO_SAVE: 200,
      FILE_SIZE_TO_RAM_COEFFCIENT: 1.5,
      FILE_SIZE_TO_SAVING_RAM_COEFFCIENT: 5,
      MIN_JS_HEAP_SIZE: 104857600,
      JS_HEAP_SIZE_LIMIT_POYFILL: 4294705152,
      ELECTRON_NOJS_MAX_MEMORY: 1503238553.6,
      MIN_TOUCH_MOVE_DISTANCE: 20,
      MIN_TWO_FINGERS_TOUCH_MOVE_DISTANCE: 10,
      MIN_SUPPORTED_SCREEN_SIZE: 1024,
      MAX_FOLDER_DEPTH_FOR_CLOUD: 64,
      OFFLINE_CHECK_MIN_WAIT: 2e3,
      USER_CHECK_MIN_WAIT: 3e4,
      SubscriptionStatus: null,
      PurchaseStatus: null,
      EXTERNAL_APP: { GOOGLEDRIVE: "googledrive" },
      DEFAULT_FILE_THUMBNAIL: "assets/img/cloud/default-file-preview.svg",
      CACHED_GAPI_FUNCTIONS: [
        "getCollaborators",
        "getFileExtended",
        "getFile",
        "getExternalFile",
      ],
      SEARCH_IN_FOLDERS: !1,
      ACTIVE_USAGE_IDLE_TIME: 3e4,
    };
  }